In [ ]:
# Python User-User Collaborative Filtering Recommender System
# consider not using pivot table?
# experiment with different similarity functions

# KNeighbors-based solution
# - For each unrated gameID that a userID has,
# - Take K-Nearest Neighbors, (Experiment with different values of K)
# - Add each Neighbor's RatingTimesSimilarityWeight, divide by K
# - Predict should return the gameIDs that have the highest scores from unrated gameIDs (top N versus some threshold)

# VERSUS BELOW (slight difference in step 3)

'''
1.) We have an n X m matrix consisting of the ratings of n users and m items. Each element of the matrix (i, j) 
represents how user i rated item j. Since we are working with movie ratings, each rating can be expected to be an 
integer from 1-5 (reflecting one-star ratings to five-star ratings) if user i has rated movie j, and 0 if the user 
has not rated that particular movie.

2.) For each user, we want to recommend a set of movies that they have not seen yet (the movie rating is 0). 
To do this, we will effectively use an approach that is similar to weighted K-Nearest Neighbors.

3.) For each movie j user i has not seen yet, we find the set of users U who are similar to user i and have seen 
movie j.
For each similar user u, we take u's rating of movie j and multiply it by the cosine similarity 
of user i and user u. Sum up these weighted ratings, divide by the number of users in U, and we get a
weighted average rating for the movie j.

4.) Finally, we sort the movies by their weighted average rankings. These average rankings serve as an estimate
for what the user will rate each movie. Movies with higher average rankings are more likely to be favored by the
user, so we will recommend the movies with the highest average rankings to the user.
'''

In [1]:
import numpy as np
import pandas as pd
import scipy
from sklearn.preprocessing import normalize

# Read CSV and change to pivot_table
df = pd.read_csv('inputs/boardgame-elite-users.csv')
df = df.pivot_table(index='userID', columns='gameID', values='rating')

# Fill nan with zero. Normalize ignores the zeroes
df = df.fillna(0)

In [ ]:
# Test / Train Split
from sklearn.model_selection import train_test_split

train, test = train_test_split(df)

In [2]:
# Normalize User Ratings for GameIDs
normalized = normalize(df)

In [3]:
# Get User Similarity Matrix
# Also try Pearson coefficient, city-block, etc...
from sklearn.metrics.pairwise import cosine_similarity

sim = cosine_similarity(df)



In [9]:
# Get K nearest neighbors
# argsort returns indices of the values of a sorted version of the array
nrst10_nbors = sim.argsort()[:,-10:-1]

print(sim)
print(len(nrst10_nbors[0]))
for x in nrst10_nbors[0]:
    print(sim[0][x])
for x in nrst10

[[1.         0.48283724 0.51777116 ... 0.4351639  0.46496088 0.43789763]
 [0.48283724 1.         0.787925   ... 0.68971905 0.76159997 0.76200811]
 [0.51777116 0.787925   1.         ... 0.66907022 0.77862168 0.74296635]
 ...
 [0.4351639  0.68971905 0.66907022 ... 1.         0.69099785 0.73612033]
 [0.46496088 0.76159997 0.77862168 ... 0.69099785 1.         0.75700164]
 [0.43789763 0.76200811 0.74296635 ... 0.73612033 0.75700164 1.        ]]
9
0.5462166510952147
0.5524040756784209
0.5530834950294008
0.5532022766035907
0.5554924637714952
0.5573424146367286
0.5803093270234448
0.5833278622108075
0.5953403235711451


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
