In [6]:
# Python User-User Collaborative Filtering Recommender System

In [11]:
import numpy as np
import pandas as pd
import scipy
from sklearn.preprocessing import normalize

df = pd.read_csv('inputs/boardgame-elite-users.csv')
df = df.pivot_table(index='userID', columns='gameID', values='rating')
# Fill nan with zero. Normalize ignores the zeroes
df = df.fillna(0)

# Normalize User Ratings for GameIDs
df = normalize(df)

[[0.02545345 0.02545345 0.02545345 ... 0.         0.         0.        ]
 [0.05955862 0.05211379 0.05955862 ... 0.07444828 0.05955862 0.05955862]
 [0.05300817 0.05300817 0.06184286 ... 0.07951225 0.07951225 0.        ]
 ...
 [0.05984758 0.07979678 0.         ... 0.07979678 0.05984758 0.        ]
 [0.05979413 0.05979413 0.05979413 ... 0.         0.05979413 0.05979413]
 [0.04614873 0.05384018 0.04614873 ... 0.         0.         0.05768591]]


In [13]:
from sklearn.metrics.pairwise import cosine_similarity

user_similarity_matrix = cosine_similarity(df)

print(user_similarity_matrix)

[[1.         0.48283724 0.51777116 ... 0.4351639  0.46496088 0.43789763]
 [0.48283724 1.         0.787925   ... 0.68971905 0.76159997 0.76200811]
 [0.51777116 0.787925   1.         ... 0.66907022 0.77862168 0.74296635]
 ...
 [0.4351639  0.68971905 0.66907022 ... 1.         0.69099785 0.73612033]
 [0.46496088 0.76159997 0.77862168 ... 0.69099785 1.         0.75700164]
 [0.43789763 0.76200811 0.74296635 ... 0.73612033 0.75700164 1.        ]]
